//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by jwpce-pocketpc.rc
//
#define IDS_ABOUT_TEXT                  1
#define IDS_ABOUT_TITLE                 2
#define IDS_AREYOUSURE                  3
#define IDS_WARNING                     4
#define IDS_ERROR_TERMINAL              5
#define IDS_ERROR                       6
#define IDS_ERROR_MEMORY                7
#define IDS_ERROR_SAVECONVERT           8
#define IDS_ERROR_CLIPTEXT              9
#define IDS_ERROR_CLIPTITLE             10
#define IDS_TERM_MENU                   11
#define IDS_TERM_POPUP                  12
#define IDS_TERM_ACCEL                  13
#define IDS_TERM_REGCLASS               14
#define IDS_TERM_WINDOW                 15
#define IDS_TERM_INITIALIZE             16
#define IDS_TERM_FONTS                  17
#define IDS_TERM_STATUS                 18
#define IDS_TERM_KANAKANJI              19
#define IDS_TERM_CONTROLS               20
#define IDS_TERM_FILEWINDOW             21
#define IDS_TERM_INFO                   22
#define IDS_TERM_LOOKUP                 23
#define IDS_TERM_STARTUP                24
#define IDS_TERM_COM                    25
#define IDS_INST_GROUP                  26
#define IDS_INST_FILETYPE               27
#define IDS_INST_PROJECTTYPE            28
#define IDS_START_CONFIGLOAD            29
#define IDS_START_CONFIGSAVE            30
#define IDS_START_CONFIGWRITE           31
#define IDS_PRINT_ERROR                 32
#define IDS_PRINT_NOPRINTERS            33
#define IDS_PRINT_ABORT                 34
#define IDS_PRINT_PAGE                  35
#define IDS_PRINT_ERRORTEXT             36
#define IDS_LANG_ID                     37
#define IDS_LANG_ERRORTEXT              38
#define IDS_LANG_ERRORTITLE             39
#define IDS_HIST_DICTIONARY             40
#define IDS_HIST_SEARCH                 41
#define IDS_HIST_REPLACE                42
#define IDS_TOOL_NEW                    43
#define IDS_TOOL_OPEN                   44
#define IDS_TOOL_SAVE                   45
#define IDS_TOOL_DELETE                 46
#define IDS_TOOL_PRINT                  47
#define IDS_TOOL_UNDO                   48
#define IDS_TOOL_REDO                   49
#define IDS_TOOL_KANJI                  50
#define IDS_TOOL_ASCII                  51
#define IDS_TOOL_JASCII                 52
#define IDS_TOOL_CUT                    53
#define IDS_TOOL_COPY                   54
#define IDS_TOOL_PASTE                  55
#define IDS_TOOL_SEARCH                 56
#define IDS_TOOL_REPLACE                57
#define IDS_TOOL_NEXT                   58
#define IDS_TOOL_REVERSE                59
#define IDS_TOOL_CONVERT                60
#define IDS_TOOL_INFO                   61
#define IDS_TOOL_RADICAL                62
#define IDS_TOOL_BUSHU                  63
#define IDS_TOOL_BS                     64
#define IDS_TOOL_SKIP                   65
#define IDS_TOOL_HS                     66
#define IDS_TOOL_FOURCORNER             67
#define IDS_TOOL_READING                68
#define IDS_TOOL_INDEX                  69
#define IDS_TOOL_JISTABLE               70
#define IDS_TOOL_COUNTKANJI             71
#define IDS_TOOL_COLORKANJI             72
#define IDS_TOOL_FORMATFILE             73
#define IDS_TOOL_FORMATPARA             74
#define IDS_TOOL_LAYOUT                 75
#define IDS_TOOL_DICTIONARY             76
#define IDS_TOOL_CONVERSIONS            77
#define IDS_TOOL_OPTIONS                78
#define IDS_TOOL_TIPS                   79
#define IDS_FILE_UNNAMED                80
#define IDS_FILE_CORRUPTED              81
#define IDS_FILE_ERROR                  82
#define IDS_FILE_LAST                   83
#define IDS_FILE_CREATEFATAL            84
#define IDS_FILE_DELETETITLE            85
#define IDS_FILE_DELETETEXT             86
#define IDS_FILE_PROJTITLE              87
#define IDS_FILE_PROJTEXT               88
#define IDS_FILE_PROJERROR              89
#define IDS_FILE_PROJCORRUP             90
#define IDS_FILE_PROJSAVE               91
#define IDS_FILE_ERRORJWPCE             92
#define IDS_FILE_REVERT                 93
#define IDS_FILE_ERRORTEMP              94
#define IDS_FILE_ERRORWRITE             95
#define IDS_FILE_OVERWRITE              96
#define IDS_FILE_FILTERSGENERAL         97
#define IDS_FILE_FILTERSOPEN            98
#define IDS_FILE_DAMMAGED               99
#define IDS_STAT_OVR                    100
#define IDS_STAT_INS                    101
#define IDS_STAT_ASCII                  102
#define IDS_STAT_KANJI                  103
#define IDS_STAT_JASCII                 104
#define IDS_STAT_HALFKANA               105
#define IDS_STAT_UNTYPED                106
#define IDS_STAT_TYPEASCII              107
#define IDS_STAT_TYPEJWPCE              108
#define IDS_STAT_TYPEJWP                109
#define IDS_STAT_TYPEEUC                110
#define IDS_STAT_TYPESJIS               111
#define IDS_STAT_TYPENEW                112
#define IDS_STAT_TYPEOLD                113
#define IDS_STAT_TYPENEC                114
#define IDS_STAT_TYPEUNICODE            115
#define IDS_STAT_TYPEUTF7               116
#define IDS_STAT_TYPEUTF8               117
#define IDS_STAT_TYPEJFC                118
#define IDS_STAT_TYPE1                  119
#define IDS_LIST_IMPORT                 120
#define IDS_LIST_IMPORTERROR            121
#define IDS_LIST_POPUP                  122
#define IDS_FP_FORMATFILE               123
#define IDS_FP_INVALIDTEXT              124
#define IDS_FP_INVALIDTITLE             125
#define IDS_CK_TEXT                     126
#define IDS_CK_TITLE                    127
#define IDS_CK_ERROR                    128
#define IDS_CK_SUMMARYTITLE             129
#define IDS_CK_SUMMARY                  130
#define IDS_CK_APPEND                   131
#define IDS_CK_REMOVE                   132
#define IDS_CK_VIEWNAME                 133
#define IDS_SR_NOTFOUND                 134
#define IDS_SR_CHANGESMADE              135
#define IDS_SR_CHANGES                  136
#define IDS_CE_ERRORTEXT                137
#define IDS_CE_ERRORTITLE               138
#define IDS_CE_ERROREMPTY               139
#define IDS_CE_ERRORKANA                140
#define IDS_CE_ERRORGODAN               141
#define IDS_CE_ERRORVERB                142
#define IDS_CE_FILETYPE                 143
#define IDS_CE_ERROROPEN                144
#define IDS_CE_CHANGEDTEXT              145
#define IDS_CE_CLOSE                    146
#define IDS_CE_ERRORRUVERB              147
#define IDS_CE_ERRORIADJ                148
#define IDS_KI_TYPEUNKNOWN              149
#define IDS_KI_TYPEASCII                150
#define IDS_KI_TYPEEXTENDED             151
#define IDS_KI_TYPESYMBOL               152
#define IDS_KI_TYPEJASCII               153
#define IDS_KI_TYPEHIRAGANA             154
#define IDS_KI_TYPEKATAKANA             155
#define IDS_KI_TYPEGREEK                156
#define IDS_KI_TYPERUSSIAN              157
#define IDS_KI_TYPERESERVED             158
#define IDS_KI_TYPEKANJI1               159
#define IDS_KI_TYPEKANJI2               160
#define IDS_KI_SKIPPOSITION             161
#define IDS_KI_SKIPSTROKE               162
#define IDS_KI_SKIPBOTH                 163
#define IDS_KI_SKIPBREEN                164
#define IDS_KI_ERRORTITLE               165
#define IDS_KI_ERROROPEN                166
#define IDS_KI_ERRORVERSION             167
#define IDS_KI_LISTMEANINGS             168
#define IDS_KI_LISTONYOMI               169
#define IDS_KI_LISTKUNYOMI              170
#define IDS_KI_LISTNANORI               171
#define IDS_KI_ITEMTYPE                 172
#define IDS_KI_ITEMJISCODE              173
#define IDS_KI_ITEMSHIFTJIS             174
#define IDS_KI_ITEMUNICODE              175
#define IDS_KI_ITEMSTROKES              176
#define IDS_KI_ITEMGRADE                177
#define IDS_KI_ITEMHELSON               178
#define IDS_KI_ITEMHALPERN              179
#define IDS_KI_ITEMSPAHN                180
#define IDS_KI_ITEMFOURCORNERS          181
#define IDS_KI_ITEMMOROHASHI            182
#define IDS_KI_ITEMPINYIN               183
#define IDS_KI_ITEMKOREAN               184
#define IDS_KI_ITEMFREQUENCY            185
#define IDS_KI_ITEMHENSHALL             186
#define IDS_KI_ITEMGAKKEN               187
#define IDS_KI_ITEMHEISIG               188
#define IDS_KI_ITEMONEILL               189
#define IDS_KI_ITEMDEROO                190
#define IDS_KI_ITEMKANJILEARN           191
#define IDS_MI_NELSON                   192
#define IDS_MI_HALPERN                  193
#define IDS_MI_ONEILL                   194
#define IDS_MI_JIS0208                  195
#define IDS_MI_JIS0212                  196
#define IDS_MI_SKIP                     197
#define IDS_MI_DEROO                    198
#define IDS_DICT_ERROR                  199
#define IDS_DICT_LANGUAGE               200
#define IDS_DICT_NAMECLASSICAL          201
#define IDS_DICT_NAMEEDICT              202
#define IDS_DICT_NAMEENAMDICT           203
#define IDS_DICT_NAMEUSER               204
#define IDS_DO_BEGIN                    205
#define IDS_DO_END                      206
#define IDS_DO_PERSONALNAMES            207
#define IDS_DO_PLACENAMES               208
#define IDS_DO_VULGAR                   209
#define IDS_DO_X                        210
#define IDS_DO_COLLOQUIAL               211
#define IDS_DO_MANGA                    212
#define IDS_DO_SLANG                    213
#define IDS_DO_MARIAL                   214
#define IDS_DO_IDIOMATIC                215
#define IDS_DO_ARCHAIC                  216
#define IDS_DO_OBSOLETE                 217
#define IDS_DO_OBSCURE                  218
#define IDS_DO_KANA                     219
#define IDS_DO_ABBREVIATION             220
#define IDS_DO_POLITE                   221
#define IDS_DO_HUMBLE                   222
#define IDS_DO_FAMILIAR                 223
#define IDS_DO_HONORIFIC                224
#define IDS_DO_FEMALE                   225
#define IDS_DO_MALE                     226
#define IDS_DO_PREFIX                   227
#define IDS_DO_SUFFIX                   228
#define IDS_DO_KANJI                    229
#define IDS_DE_ERROR                    230
#define IDS_DE_ERRORKANA                231
#define IDS_DE_ERRORNONKANA             232
#define IDS_DE_ERRORMEANING             233
#define IDS_DE_FILETYPE                 234
#define IDS_DE_ERROROPEN                235
#define IDS_DS_ERROR                    236
#define IDS_DS_ERRORNOTDICT             237
#define IDS_DS_ALREADYTEXT              238
#define IDS_DS_ALREADYTITLE             239
#define IDS_DS_ERROROPEN                240
#define IDS_DS_FILETYPE                 241
#define IDS_DS_ERROREMPTY               242
#define IDS_DS_DOESNOTEXIST             243
#define IDS_DD_CLASSICAL                244
#define IDR_MAINMENU                    244
#define IDS_DD_CANNOTOPEN               245
#define IDR_MAINMENU2                   245
#define IDS_DD_MATCHREJECT              246
#define IDS_DD_MATCH                    247
#define IDS_DD_DICTINDEX                248
#define IDS_DD_SEARCHING                249
#define IDS_DD_ERRORLENGTH              250
#define IDS_DD_ERRORASCIIKANA           251
#define IDS_DD_ABORTREJECT              252
#define IDS_DD_ABORT                    253
#define IDS_DD_NOMATCH                  254
#define IDS_DD_NOKANJI                  255
#define IDS_DD_ADVANCED                 256
#define IDS_DU_CHANGEDTEXT              257
#define IDS_DU_CLOSE                    258
#define IDS_DC_FORMATEUC                259
#define IDS_DC_FORMATUTF8               260
#define IDS_DC_FORMATMIXED              261
#define IDS_DC_ERR                      262
#define IDS_DC_YES                      263
#define IDS_DC_NO                       264
#define IDS_DC_NONAMES                  265
#define IDS_DC_NAMES                    266
#define IDS_DC_NAMESONLY                267
#define IDS_DC_CLASSICAL                268
#define IDS_DC_USER                     269
#define IDS_DC_COLUMNNAME               270
#define IDS_DC_COLUMNFORMAT             271
#define IDS_DC_COLUMNINDEX              272
#define IDS_DC_COLUMNNAMES              273
#define IDS_DC_COLUMNSPECIAL            274
#define IDS_DC_COLUMNFILE               275
#define IDS_DC_COLUMNTYPE               276
#define IDS_DC_TYPEIDX                  277
#define IDS_DC_TYPEBUF                  278
#define IDS_DC_TYPEMEM                  279
#define IDS_DC_COLUMNKEEP               280
#define IDS_DC_COLUMNQUIET              281
#define IDS_RL_NONE                     282
#define IDS_RL_TOOMANY                  283
#define IDS_IL_NELSON                   284
#define IDS_IL_HAIG                     285
#define IDS_IL_HALPERN                  286
#define IDS_IL_GRADE                    287
#define IDS_IL_MOROHASHILONG            288
#define IDS_IL_MOROHASHISHORT           289
#define IDS_IL_SPAHN                    290
#define IDS_IL_HENSHALL                 291
#define IDS_IL_GAKKEN                   292
#define IDS_IL_HEISIG                   293
#define IDS_IL_ONEILL                   294
#define IDS_IL_FREQUENCY                295
#define IDS_IL_RESERVED                 296
#define IDS_KI_BLANK                    296
#define IDS_IL_DEROO                    297
#define IDS_IL_ONEILLEK                 298
#define IDS_IL_HALPERNKLD               299
#define IDS_RL_ERRORRADINDEX            300
#define IDS_RL_ERROR                    301
#define IDS_RL_ERRORTEXT                302
#define IDS_RL_ERRORSTRINDEX            303
#define IDS_RL_ON                       304
#define IDS_RL_KUN                      305
#define IDS_RL_ONKUN                    306
#define IDS_RL_MEANING                  307
#define IDS_RL_NANORI                   308
#define IDS_RL_PINYIN                   309
#define IDS_RL_KOREAN                   310
#define IDS_RL_ERRORKANA                311
#define IDS_RL_ERRORKANAFOUND           312
#define IDS_RL_ERRORNONKANA             313
#define IDS_OPTS_GENERAL                314
#define IDS_OPTS_DISPLAY                315
#define IDS_OPTS_FONT                   316
#define IDS_OPTS_FILECLIP               317
#define IDS_OPTS_MISC                   318
#define IDS_OPTS_ADVANCED               319
#define IDS_OF_JIS                      320
#define IDS_OF_SYSTEM                   321
#define IDS_OF_EDIT                     322
#define IDS_OF_LIST                     323
#define IDS_OF_BAR                      324
#define IDS_OF_FILE                     325
#define IDS_OF_BIG                      326
#define IDS_OF_PRINT                    327
#define IDS_OF_CLIP                     328
#define IDS_OF_PIXELS                   329
#define IDS_OF_POINTS                   330
#define IDS_OC_AUTO                     331
#define IDS_OC_EUC                      332
#define IDS_OC_SHIFTJIS                 333
#define IDS_OC_NEWJIS                   334
#define IDS_OC_OLDJIS                   335
#define IDS_OC_NECJIS                   336
#define IDS_OC_UNICODE                  337
#define IDS_OC_UTF7                     338
#define IDS_OC_UTF8                     339
#define IDS_LAYOUT_MARGINS              340
#define IDS_LAYOUT_HEADFOOT             341
#define IDS_LAYOUT_SUMMARY              342
#define IDS_LAYOUT_DATETIME             343
#define IDS_LAYOUT_ADVANCED             344
#define IDS_LH_HEADODD                  345
#define IDS_LH_HEADEVEN                 346
#define IDS_LH_FOOTODD                  347
#define IDS_LH_FOOTEVEN                 348
#define IDS_LH_HEADER                   349
#define IDS_LH_FOOTER                   350
#define IDS_LM_CM                       351
#define IDS_LM_INCH                     352
#define IDS_IL_READWRITE                353
#define IDS_IL_TUTTLECARD               354
#define IDS_IL_KANJIWAY                 355
#define IDS_IL_KANJICONTEXT             356
#define IDS_IL_BUSYPEOPLE               357
#define IDS_IL_COMPACTKANJI             358
#define IDS_KI_READWRITE                359
#define IDS_KI_TUTTLECARD               360
#define IDS_KI_KANJIWAY                 361
#define IDS_KI_KANJICONTEXT             362
#define IDS_KI_BUSYPEOPLE               363
#define IDS_KI_COMPACTGUIDE             364
#define IDS_KI_BUSYFORMAT               365
#define IDS_CP_AUTO                     366
#define IDS_CP_EASTEUROPE               367
#define IDS_CP_CYRILLIC                 368
#define IDS_CP_USA                      369
#define IDS_CP_GREEK                    370
#define IDS_CP_TURKISH                  371
#define IDS_CP_HEBREW                   372
#define IDS_CP_ARABIC                   373
#define IDS_CP_BALTIC                   374
#define IDS_CP_VIETNAMESE               375
#define IDA_MAINACCEL                   800
#define IDM_MAINMENU                    820
#define IDM_POPUP                       821
#define IDR_BUTTONBAR                   822
#define IDB_CURSOR                      841
#define IDB_RADICALS                    842
#define IDB_STROKES                     843
#define IDB_SKIPTYPES                   844
#define IDB_FCSHAPES                    845
#define IDB_HSRADICALS                  846
#define IDB_RADLOOKUP                   847
#define IDB_BUSHULOOKUP                 848
#define IDB_DICTIONARY                  849
#define IDB_KANJICONVERT                850
#define IDB_CHARINFO                    851
#define IDB_RIGHTLEFT                   852
#define IDB_RIGHTLEFT1                  853
#define IDB_TOOLBAR                     854
#define IDB_HPCTOOLS                    855
#define IDB_PPCTOOLS                    856
#define IDI_MAINICON                    880
#define IDI_FILEICON                    881
#define IDI_ALTICON                     882
#define IDI_ICON1                       883
#define IDI_PROJECTICON                 883
#define IDD_ADVINSTALL                  900
#define IDD_CONVERTEDIT                 901
#define IDD_DICTIONARIES                902
#define IDD_DICTIONARY                  903
#define IDD_DICTOPTIONS                 904
#define IDD_DUPLICATE                   905
#define IDD_DICTUSEREDIT                906
#define IDD_DICTEDITDICTIONARIES        907
#define IDD_FILES                       908
#define IDD_FORMATPARA                  909
#define IDD_REPLACECONFIRM              910
#define IDD_SAVECHECK                   911
#define IDD_INSTALL                     912
#define IDD_JISTABLE                    913
#define IDD_KANJICOUNT                  914
#define IDD_KANJIINFO                   915
#define IDD_PRINTING                    916
#define IDD_RADICALLOOKUP               917
#define IDD_REPLACE                     918
#define IDD_DICTUSER                    919
#define IDD_SEARCH                      920
#define IDD_CONVERTUSER                 921
#define IDD_LAYOUTADVANCED              922
#define IDD_LAYOUTDATE                  923
#define IDD_LAYOUTHEADER                924
#define IDD_LAYOUTMARGINS               925
#define IDD_LAYOUTSUMMARY               926
#define IDD_OPTIONS                     927
#define IDD_OPTADVANCED                 928
#define IDD_OPTDISPLAY                  929
#define IDD_OPTFILE                     930
#define IDD_OPTFONT                     931
#define IDD_OPTGENERAL                  932
#define IDD_OPTMISC                     933
#define IDD_CHOOSECOLOR                 934
#define IDD_LAYOUT                      935
#define IDD_OPTIONS1                    936
#define IDD_MOREINFO                    937
#define IDD_SKIPLOOKUP                  938
#define IDD_FCLOOKUP                    939
#define IDD_BUSHULOOKUP                 940
#define IDD_KANJIVIEW                   941
#define IDD_INDEXLOOKUP                 942
#define IDD_XREFINFO                    943
#define IDD_READINGLOOKUP               944
#define IDD_HSLOOKUP                    945
#define IDD_BUSHU2LOOKUP                946
#define IDD_ADDCOLORKANJI               947
#define IDD_INFOCONFIG                  948
#define IDD_HISTORY                     949
#define IDSEARCH                        999
#define IDC_CKALL                       1000
#define IDC_CKEXCLUDE                   1001
#define IDC_CKINCLUDE                   1002
#define IDC_CKFREQUENCY                 1003
#define IDC_CKONYOMI                    1004
#define IDC_CKKUNYOMI                   1005
#define IDC_CKMEANING                   1006
#define IDC_CKNUMBER                    1007
#define IDC_CKINFO                      1008
#define IDC_CKINSERT                    1009
#define IDC_CKLIST                      1010
#define IDC_AIJCE                       1020
#define IDC_AIJWP                       1021
#define IDC_AIEUC                       1022
#define IDC_AISJS                       1023
#define IDC_AIJIS                       1024
#define IDC_AIOLD                       1025
#define IDC_AINEC                       1026
#define IDC_AIUTF                       1027
#define IDC_AIJCP                       1028
#define IDC_AIJFC                       1029
#define IDC_AISTART                     1030
#define IDC_AIDESKTOP                   1031
#define IDC_AIGROUP                     1032
#define IDC_CEKANA                      1040
#define IDC_CEKANJI                     1041
#define IDC_CEGODAN                     1042
#define IDC_CEICHIDAN                   1043
#define IDC_CEIADJ                      1044
#define IDC_DEKANA                      1050
#define IDC_DEKANJI                     1051
#define IDC_DEMEANING                   1052
#define IDC_DSSEARCH                    1060
#define IDC_DSNAMES                     1061
#define IDC_DSINDEX                     1062
#define IDC_DSONLY                      1063
#define IDC_DSDESCRIPTION               1064
#define IDC_DSFILE                      1065
#define IDC_DSBROWSE                    1066
#define IDC_DSNAME                      1067
#define IDC_DSEUC                       1068
#define IDC_DSUTF8                      1069
#define IDC_DSMIXED                     1070
#define IDC_DSMEMORY                    1071
#define IDC_DSBUFFER                    1072
#define IDC_DSNONAMES                   1073
#define IDC_DSUSER                      1074
#define IDC_DSCLASSICAL                 1075
#define IDC_DSKEEP                      1076
#define IDC_DSUPDATE                    1077
#define IDC_DSAUTO                      1078
#define IDC_DSQUIET                     1079
#define IDC_DDSTRING                    1080
#define IDC_DDRESULT                    1081
#define IDC_DDBEGIN                     1082
#define IDC_DDEND                       1083
#define IDC_DDNONAME                    1084
#define IDC_DDNOPLACE                   1085
#define IDC_DDADVANCED                  1085
#define IDC_DDUSER                      1086
#define IDC_DDOPTIONS                   1087
#define IDC_DDINSERT                    1088
#define IDC_DDSTATUS                    1089
#define IDC_DDHISTORY                   1090
#define IDC_DDSORT                      1091
#define IDC_DDCLASSICAL                 1092
#define IDC_DDFULLASCII                 1093
#define IDC_DDPRIORITY                  1094
#define IDC_DDCLIPBOARD                 1095
#define IDC_DDADVALWAYS                 1096
#define IDC_DDADVALL                    1097
#define IDC_DDADVI                      1098
#define IDC_DDMARK                      1099
#define IDC_DDJASCII                    1100
#define IDC_DOEXCLUDE                   1120
#define IDC_DOCOMPRESS                  1121
#define IDC_DOAUTO                      1122
#define IDC_DODICTIONARIES              1123
#define IDC_DOUSERDICT                  1124
#define IDC_DOADVSEARCH                 1125
#define IDC_DOADVI                      1126
#define IDC_DOADVALWAYS                 1127
#define IDC_DOADVALL                    1128
#define IDC_DOMARK                      1129
#define IDC_DOCLIPBOARD                 1130
#define IDC_DOCLASSICAL                 1131
#define IDC_DOPRIMARY                   1132
#define IDC_DOFULLASCII                 1133
#define IDC_DOJASCII                    1134
#define IDC_FPLEFT                      1140
#define IDC_FPRIGHT                     1141
#define IDC_FPFIRST                     1142
#define IDC_FPSPACING                   1143
#define IDC_RLRADICALS                  1180
#define IDC_RLCLEAR                     1181
#define IDC_RLINFO                      1182
#define IDC_RLINSERT                    1183
#define IDC_RLANY                       1184
#define IDC_RLPM2                       1185
#define IDC_RLPM1                       1186
#define IDC_RLAUTO                      1187
#define IDC_RLRESULT                    1188
#define IDC_RLMESSAGE                   1189
#define IDC_RLSTROKE                    1190
#define IDC_RLSPIN                      1191
#define IDC_RLCOPY                      1192
#define IDC_RLCOPYKANJI                 1193
#define IDC_JTJISCODE                   1210
#define IDC_JTEUCCODE                   1211
#define IDC_JTSJISCODE                  1212
#define IDC_JTUNICODE                   1213
#define IDC_JTINFO                      1214
#define IDC_JTINSERT                    1215
#define IDC_JTTABLE                     1216
#define IDC_JTCLIP                      1217
#define IDC_LAPOSHEADLEFT               1220
#define IDC_LAPOSHEADRIGHT              1221
#define IDC_LAPOSHEADTOP                1222
#define IDC_LAPOSHEADBOTTOM             1223
#define IDC_LAJUSTIFY                   1224
#define IDC_LDDATE                      1230
#define IDC_LDTIME                      1231
#define IDC_LDAM                        1232
#define IDC_LDPM                        1233
#define IDC_LHNOFIRST                   1240
#define IDC_LHODDEVEN                   1241
#define IDC_LHEDIT                      1242
#define IDC_LHHEADLEFT                  1250
#define IDC_LHHEADCENTER                1251
#define IDC_LHHEADRIGHT                 1252
#define IDC_LHCODES                     1253
#define IDC_LMFLEFT                     1260
#define IDC_LMFRIGHT                    1261
#define IDC_LMFTOP                      1262
#define IDC_LMFBOTTOM                   1263
#define IDC_LMFVERTICAL                 1264
#define IDC_LMFLANDSCAPE                1265
#define IDC_LMFROMDEFAULT               1266
#define IDC_LMFUNITS                    1267
#define IDC_LMFWIDTH                    1268
#define IDC_LMDLEFT                     1270
#define IDC_LMDRIGHT                    1271
#define IDC_LMDTOP                      1272
#define IDC_LMDBOTTOM                   1273
#define IDC_LMDVERTICAL                 1274
#define IDC_LMDLANDSCAPE                1275
#define IDC_LMFROMFILE                  1276
#define IDC_LMDUNITS                    1277
#define IDC_LMDWIDTH                    1278
#define IDC_LSTITLE                     1290
#define IDC_LSSUBJECT                   1291
#define IDC_LSAUTHOR                    1292
#define IDC_LSKEYWORDS                  1293
#define IDC_LSCOMMENTS                  1294
#define IDC_PSNAME                      1300
#define IDC_PSMESSAGE                   1301
#define IDC_OGRESTOREPOS                1310
#define IDC_OGRELOADFILES               1311
#define IDC_OGSAVESETTINGS              1312
#define IDC_OGCONFIRMEXIT               1313
#define IDC_OGWIDTHDYNAMIC              1314
#define IDC_OGWIDTHFIXED                1315
#define IDC_OGWIDTHPRINTER              1316
#define IDC_OGCLOSEFILE                 1317
#define IDC_OGCLOSEPROGRAM              1318
#define IDC_OGWIDTH                     1319
#define IDC_OGINCHES                    1321
#define IDC_OGCM                        1322
#define IDC_OGPAGEFILE                  1323
#define IDC_OGPAGELIST                  1324
#define IDC_ODVSCROLL                   1330
#define IDC_ODHSCROLL                   1331
#define IDC_ODKSCROLL                   1332
#define IDC_ODSTATUSBAR                 1333
#define IDC_ODKBARTOP                   1334
#define IDC_ODSTATUSABOVE               1335
#define IDC_ODHIGHLIGHT                 1336
#define IDC_ODHIGHLIGHTBOX              1337
#define IDC_ODTOOLBAR                   1338
#define IDC_ODSCROLLSPEED               1339
#define IDC_ODAUTOSCROLL                1340
#define IDC_ODKANJIBAR                  1341
#define IDC_OFASCIIFONT                 1350
#define IDC_OFDISPLAYFONT               1351
#define IDC_OFPRINTFONT                 1352
#define IDC_OFRELAXPUNCT                1353
#define IDC_OFRELAXSMALL                1354
#define IDC_OFAUTOFONT                  1355
#define IDC_OFPRINTSIZE                 1356
#define IDC_OFASCIINAME                 1357
#define IDC_OFHEIGHT                    1358
#define IDC_OFALL                       1359
#define IDC_OFSHOWALL                   1359
#define IDC_OFFONT                      1360
#define IDC_OFVERTICAL                  1361
#define IDC_OFHLABEL                    1362
#define IDC_OFFONTNAME                  1363
#define IDC_OFAUTO                      1364
#define IDC_OCSAVEBACKUP                1370
#define IDC_OCCLIPIMPORT                1371
#define IDC_OCCLIPEXPORT                1372
#define IDC_OCDUPOPEN                   1373
#define IDC_OCDUPCHANGE                 1374
#define IDC_OCDUPPROMPT                 1375
#define IDC_OCNOBITMAP                  1376
#define IDC_OCNOUNICODE                 1377
#define IDC_OMINFOTITLES                1390
#define IDC_OMRADSELINFO                1391
#define IDC_OMRADSELINSERT              1392
#define IDC_OMCOLORKANJI                1393
#define IDC_OMINLIST                    1394
#define IDC_OMNOTINLIST                 1395
#define IDC_OMKANJICOLOR                1396
#define IDC_OMCOLORBITMAP               1397
#define IDC_OMCOLORPRINT                1398
#define IDC_OMINSERTLINE                1399
#define IDC_OMKANJIBOX                  1400
#define IDC_OMINFOCOMPRESS              1401
#define IDC_OMSINGLEINFO                1402
#define IDC_OMINFOSETUP                 1403
#define IDC_OAALLOCSIZE                 1410
#define IDC_OACONVERTSIZE               1411
#define IDC_OAUNDOLEVELS                1412
#define IDC_OAFONTCACHE                 1414
#define IDC_OACACHEDISPLAY              1415
#define IDC_OACACHEINFO                 1416
#define IDC_OABUFFER                    1417
#define IDC_OASEARCHOPEN                1418
#define IDC_OAHISTORY                   1419
#define IDC_OACODEPAGE                  1420
#define IDC_SRSEARCH                    1430
#define IDC_SRREPLACE                   1431
#define IDC_SRCASE                      1432
#define IDC_SRJASCII                    1433
#define IDC_SRBACKWARD                  1434
#define IDC_SRWRAP                      1435
#define IDC_SRALLFILES                  1436
#define IDC_SRNOCONFIRM                 1437
#define IDC_SRHISTSEARCH                1438
#define IDC_SRHISTREPLACE               1439
#define IDC_RCNOREP                     1450
#define IDC_RCALL                       1451
#define IDC_CCSAMPLE                    1470
#define IDC_CCRED                       1471
#define IDC_CCREDSPIN                   1472
#define IDC_CCGREEN                     1473
#define IDC_CCGREENSPIN                 1474
#define IDC_CCBLUE                      1475
#define IDC_CCBLUESPIN                  1476
#define IDC_CCBOX1                      1477
#define IDC_CCBOX2                      1478
#define IDC_CCBOX3                      1479
#define IDC_CCBOX4                      1480
#define IDC_CCBOX5                      1481
#define IDC_CCBOX6                      1482
#define IDC_CCBOX7                      1483
#define IDC_CCBOX8                      1484
#define IDC_CCBOX9                      1485
#define IDC_CCBOX10                     1486
#define IDC_CCBOX11                     1487
#define IDC_CCBOX12                     1488
#define IDC_CCBOX13                     1489
#define IDC_CCBOX14                     1490
#define IDC_CCBOX15                     1491
#define IDC_CCBOX16                     1492
#define IDC_CCBOX17                     1493
#define IDC_CCBOX18                     1494
#define IDC_CCBOX19                     1495
#define IDC_CCBOX20                     1496
#define IDC_CCBOX21                     1497
#define IDC_CCBOX22                     1498
#define IDC_CCBOX23                     1499
#define IDC_CCBOX24                     1500
#define IDC_MIXREF                      1510
#define IDC_MINEXT                      1511
#define IDC_MIINSERT                    1512
#define IDC_SLTYPE                      1520
#define IDC_SLTYPESPIN                  1521
#define IDC_SLS1                        1522
#define IDC_SLS1SPIN                    1523
#define IDC_SLS2                        1524
#define IDC_SLS2SPIN                    1525
#define IDC_SLMISSCODES                 1526
#define IDC_SLSKIPTYPE                  1527
#define IDC_FC1                         1540
#define IDC_FC1SPIN                     1541
#define IDC_FC2                         1542
#define IDC_FC2SPIN                     1543
#define IDC_FC3                         1544
#define IDC_FC3SPIN                     1545
#define IDC_FC4                         1546
#define IDC_FC4SPIN                     1547
#define IDC_FC5                         1548
#define IDC_FC5SPIN                     1549
#define IDC_FCSHAPES                    1550
#define IDC_BLNELSON                    1560
#define IDC_BLCLASSICAL                 1561
#define IDC_BLSTROKE                    1562
#define IDC_BLSPIN                      1563
#define IDC_ILTYPE                      1580
#define IDC_ILINDEX                     1581
#define IDC_ILVOL                       1582
#define IDC_RLTYPE                      1600
#define IDC_RLKUN                       1601
#define IDC_RLSTRING                    1602
#define IDC_RLWORD                      1603
#define IDC_HSRADSTROKE                 1620
#define IDC_HSRADSRKSPIN                1621
#define IDC_HSRADICAL                   1622
#define IDC_HSRADSPIN                   1623
#define IDC_HSOTHER                     1624
#define IDC_HSOTHERSPIN                 1625
#define IDC_HSKANJI                     1626
#define IDC_HSKANJISPIN                 1627
#define IDC_HSVARIANTS                  1628
#define IDC_HSRADCHAR                   1629
#define IDC_AKDELETE                    1640
#define IDC_AKKANA                      1641
#define IDC_AKKANJI                     1641
#define IDC_HLLIST                      1660
#define IDC_DCLIST                      1670
#define IDC_DCDEFAULT                   1671
#define IDC_UDSORT                      1680
#define IDC_TABCONTROL                  1700
#define IDC_TABHELP                     1701
#define IDC_DFOPEN                      1720
#define IDC_DFREPLACE                   1721
#define IDC_UCSORT                      1740
#define IDC_IDADVANCED                  1760
#define IDC_IDINSTALL                   1761
#define IDC_SCSAVE                      1780
#define IDC_SCNO                        1781
#define IDC_FDFILES                     1800
#define IDC_EDITLIST                    2000
#define IDC_EDITLISTADD                 2001
#define IDC_EDITLISTEDIT                2002
#define IDC_EDITLISTDELETE              2003
#define IDC_EDITLISTUP                  2004
#define IDC_EDITLISTDOWN                2005
#define IDC_EDITLISTIMPORT              2006
#define IDC_EDITLISTINSERT              2007
#define IDC_EDITLISTFIND                2008
#define IDC_EDITLISTNEXT                2009
#define IDC_EDITMODE                    2100
#define IDC_DATA                        2200
#define IDC_KILIST                      2300
#define IDC_KIFROMCLIP                  2301
#define IDC_KIINSERT                    2302
#define IDC_KIBIGKANJI                  2303
#define IDC_KIMORE                      2304
#define IDC_KITYPE                      2305
#define IDC_KIXREF                      2306
#define IDC_KIBUSHU                     2307
#define IDC_KIBUSHUCHAR                 2308
#define IDC_KICLASSICALCHAR             2309
#define IDC_EDIT1                       2342
#define IDC_CHECK1                      2343
#define IDC_KILABEL0                    2400
#define IDC_KIITEM0                     2401
#define IDC_KILABEL1                    2402
#define IDC_KIITEM1                     2403
#define IDC_KILABEL2                    2404
#define IDC_KIITEM2                     2405
#define IDC_KILABEL3                    2406
#define IDC_KIITEM3                     2407
#define IDC_KILABEL4                    2408
#define IDC_KIITEM4                     2409
#define IDC_KILABEL5                    2410
#define IDC_KIITEM5                     2411
#define IDC_KILABEL6                    2412
#define IDC_KIITEM6                     2413
#define IDC_KILABEL7                    2414
#define IDC_KIITEM7                     2415
#define IDC_KILABEL8                    2416
#define IDC_KIITEM8                     2417
#define IDC_KILABEL9                    2418
#define IDC_KIITEM9                     2419
#define IDC_KILABEL10                   2420
#define IDC_KIITEM10                    2421
#define IDC_KILABEL11                   2422
#define IDC_KIITEM11                    2423
#define IDC_KILABEL12                   2424
#define IDC_KIITEM12                    2425
#define IDC_KILABEL13                   2426
#define IDC_KIITEM13                    2427
#define IDC_KILABEL14                   2428
#define IDC_KIITEM14                    2429
#define IDC_KILABEL15                   2430
#define IDC_KIITEM15                    2431
#define IDC_KILABEL16                   2432
#define IDC_KIITEM16                    2433
#define IDC_KILABEL17                   2434
#define IDC_KIITEM17                    2435
#define IDC_KILABEL18                   2436
#define IDC_KIITEM18                    2437
#define IDC_KILABEL19                   2438
#define IDC_KIITEM19                    2439
#define IDC_KILABEL20                   2440
#define IDC_KIITEM20                    2441
#define IDC_KILABEL21                   2442
#define IDC_KIITEM21                    2443
#define IDC_KILABEL22                   2444
#define IDC_KIITEM22                    2445
#define IDC_KILABEL23                   2446
#define IDC_KIITEM23                    2447
#define IDC_KILABEL24                   2448
#define IDC_KIITEM24                    2449
#define IDC_KILABEL25                   2450
#define IDC_KIITEM25                    2451
#define IDC_KILABEL26                   2452
#define IDC_KIITEM26                    2453
#define IDC_KILABEL27                   2454
#define IDC_KIITEM27                    2455
#define IDC_KILABEL28                   2456
#define IDC_KIITEM28                    2457
#define IDC_KILABEL29                   2458
#define IDC_KIITEM29                    2459
#define IDC_KILABEL30                   2460
#define IDC_KIITEM30                    2461
#define IDC_ICDEFAULT                   2500
#define IDC_ICITEM0                     2501
#define IDC_ICITEM1                     2502
#define IDC_ICITEM2                     2503
#define IDC_ICITEM3                     2504
#define IDC_ICITEM4                     2505
#define IDC_ICITEM5                     2506
#define IDC_ICITEM6                     2507
#define IDC_ICITEM7                     2508
#define IDC_ICITEM8                     2509
#define IDC_ICITEM9                     2510
#define IDC_ICITEM10                    2511
#define IDC_ICITEM11                    2512
#define IDC_ICITEM12                    2513
#define IDC_ICITEM13                    2514
#define IDC_ICITEM14                    2515
#define IDC_ICITEM15                    2516
#define IDC_ICITEM16                    2517
#define IDC_ICITEM17                    2518
#define IDC_ICITEM18                    2519
#define IDC_ICITEM19                    2520
#define IDC_ICITEM20                    2521
#define IDC_ICITEM21                    2522
#define IDC_ICITEM22                    2523
#define IDC_ICITEM23                    2524
#define IDC_ICITEM24                    2525
#define IDC_ICITEM25                    2526
#define IDC_ICITEM26                    2527
#define IDC_ICITEM27                    2528
#define IDC_ICITEM28                    2529
#define IDC_ICITEM29                    2530
#define IDC_ICITEM30                    2531
#define IDM_FILE_NEW                    10001
#define IDM_FILE_OPEN                   10002
#define IDM_FILE_REVERT                 10003
#define IDM_FILE_CLOSE                  10004
#define IDM_FILE_CLOSEALL               10005
#define IDM_FILE_SAVE                   10006
#define IDM_FILE_SAVEALL                10007
#define IDM_FILE_SAVEAS                 10008
#define IDM_FILE_PRINT                  10009
#define IDM_FILE_PRINTERSETUP           10010
#define IDM_FILE_EXIT                   10011
#define IDM_FILE_FILES_NONE             10012
#define IDM_EDIT_UNDO                   10013
#define IDM_EDIT_REDO                   10014
#define IDM_EDIT_CUT                    10015
#define IDM_EDIT_COPY                   10016
#define IDM_EDIT_PASTE                  10017
#define IDM_EDIT_SELECTALL              10018
#define IDM_EDIT_INSERTPAGEBREAK        10019
#define IDM_EDIT_SEARCH                 10020
#define IDM_EDIT_REPLACE                10021
#define IDM_EDIT_FINDNEXT               10022
#define IDM_EDIT_REVERSESEARCH          10023
#define IDM_EDIT_MODE_KANJI             10024
#define IDM_EDIT_MODE_ASCII             10025
#define IDM_EDIT_MODE_JASCII            10026
#define IDM_KANJI_CONVERT               10027
#define IDM_KANJI_RADICALLOOKUP         10028
#define IDM_KANJI_GETINFO               10029
#define IDM_KANJI_JISTABLE              10030
#define IDM_KANJI_COUNTKANJI            10031
#define IDM_KANJI_MAKEKANJILIST         10032
#define IDM_KANJI_CLEARKANJILIST        10033
#define IDM_UTILITIES_FORMATFILE        10034
#define IDM_UTILITIES_FORMATPARAGRAPH   10035
#define IDM_UTILITIES_PAGELAYOUT        10036
#define IDM_UTILITIES_DICTIONARY        10037
#define IDM_UTILITIES_VOCABLIST         10038
#define IDM_UTILITIES_USERCONVERSION    10039
#define IDM_UTILITIES_OPTIONS           10040
#define IDM_UTILITIES_DEFAULTOPTIONS    10041
#define IDM_UTILITIES_SAVESETTINGS      10042
#define IDM_UTILITIES_INSTALL           10043
#define IDM_WINDOW_NEXTFILE             10044
#define IDM_WINDOW_PREVIOUSFILE         10045
#define IDM_WINDOW_FILES                10046
#define IDM_HELP_MAININDEX              10047
#define IDM_HELP_ABOUTJWPCE             10048
#define IDM_FILE_FILES_BASE             20000
#define IDM_WINDOW_FILES_BASE           21000
#define IDM_LIST_GETINFO                30001
#define IDM_LIST_REPLACETOFILE          30002
#define IDM_LIST_COPY                   30003
#define IDM_LIST_INSERTTOFILE           30004
#define IDM_LIST_INSERTTONEWFILE        30005
#define IDM_LIST_INSERTTOANYFILE        30006
#define IDM_LIST_INSERTTO               30007
#define IDM_EDIT_MODE_TOGGLE            40056
#define IDM_FILE_DELETE                 40058
#define IDM_KANJI_SKIPLOOKUP            40059
#define IDM_KANJI_FCLOOKUP              40060
#define IDM_KANJI_BUSHULOOKUP           40061
#define IDM_KANJI_READINGLOOKUP         40062
#define IDM_KANJI_INDEXLOOKUP           40063
#define IDM_KANJI_HSLOOKUP              40064
#define IDM_KANJI_BUSHU2LOOKUP          40065
#define IDM_UTILITIES_TOGGLE            40066
#define IDM_UTILITIES_CUSTOMIZE         40067
#define IDM_KANJI_ADDSUBKANJILIST       40068
#define IDM_KANJI_APPENDKANJILIST       40069
#define IDM_KANJI_OPENKANJILIST         40070
#define IDM_UTILITIES_CHARINFO          40071
#define ID_FILE                         40072
#define IDS_CAP_FILE                    40074
#define ID_EDIT                         40075
#define IDS_CAP_EDIT                    40077
#define ID_KAN                          40078
#define IDS_CAP_KAN                     40080
#define ID_UTIL                         40081
#define IDS_CAP_UTIL                    40083
#define ID_WIN                          40084
#define IDS_CAP_WIN                     40086
#define ID_HELPX                        40088
#define IDS_CAP_HELP                    40089
#define IDS_CAP_MENUITEM40090           40091

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        247
#define _APS_NEXT_COMMAND_VALUE         40092
#define _APS_NEXT_CONTROL_VALUE         2346
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
